from __future__ import annotations
from app.features.sustainability.core import (
    ActionTemplate,
    ImpactCategory,
    ImpactVector,
)

LIBRARY: list[ActionTemplate] = [
    ActionTemplate(
        action_id="waste_bag_for_bin",
        title="Line your bin with a bag; rinse out recyclables",
        category=ImpactCategory.WASTE,
        impact=ImpactVector(kg=0.15, items=1.0),
        execution_unit="per-day",
        baseline_effort=2,
        cost_usd=0.0,
        duration_minutes=5,
        needs_learning=False,
        description="Removing contamination keeps recyclables out of landfill.",
    ),
    ActionTemplate(
        action_id="waste_compost_kitchen",
        title="Start a kitchen compost collection",
        category=ImpactCategory.WASTE,
        impact=ImpactVector(kg=0.35, kg_food=0.3),
        execution_unit="per-day",
        baseline_effort=4,
        cost_usd=2.0,
        duration_minutes=8,
        needs_learning=True,
        setup_minutes=45,
        description="Slash the organic share of your waste; feeds soil instead.",
    ),
    ActionTemplate(
        action_id="waste_shopping_list",
        title="Plan meals and shop with a list (no spontaneous buys)",
        category=ImpactCategory.WASTE,
        impact=ImpactVector(kg=0.20, kg_food=0.15),
        execution_unit="per-week",
        baseline_effort=4,
        cost_usd=0.0,
        duration_minutes=20,
        needs_learning=False,
        description="Prevents the 'bought and never eaten' bucket.",
    ),
    ActionTemplate(
        action_id="waste_bulky_spend",
        title="Repair or buy one durable item instead of a disposable one",
        category=ImpactCategory.WASTE,
        impact=ImpactVector(kg=0.5, items=1.0),
        execution_unit="per-week",
        baseline_effort=5,
        cost_usd=10.0,
        duration_minutes=30,
        needs_learning=True,
        description="Extend the life of one thing; a repair café or a quality replacement.",
    ),
    ActionTemplate(
        action_id="waste_compact_separate",
        title="Separate one extra material for a local drop-off",
        category=ImpactCategory.WASTE,
        impact=ImpactVector(kg=0.4),
        execution_unit="per-week",
        baseline_effort=3,
        cost_usd=0.0,
        duration_minutes=15,
        needs_learning=True,
        description="Find one stream near you (e-waste, textiles, batteries, soft plastics).",
    ),
    ActionTemplate(
        action_id="energy_led_swap",
        title="Swap one bulb to LED",
        category=ImpactCategory.ENERGY,
        impact=ImpactVector(kwh=0.35),
        execution_unit="one-time",
        baseline_effort=2,
        cost_usd=4.0,
        duration_minutes=10,
        needs_learning=False,
        description="Cut lighting waste for years for a few dollars.",
    ),
    ActionTemplate(
        action_id="energy_shower_timer",
        title="Set a shower timer and stick to 5 minutes",
        category=ImpactCategory.ENERGY,
        impact=ImpactVector(kwh=0.3, litres=30.0),
        execution_unit="per-day",
        baseline_effort=3,
        cost_usd=0.0,
        duration_minutes=1,
        needs_learning=False,
        description="Hot water is energy; shorter showers cut both.",
    ),
    ActionTemplate(
        action_id="energy_extinct_standby",
        title="Unplug standby devices for the day",
        category=ImpactCategory.ENERGY,
        impact=ImpactVector(kwh=0.15),
        execution_unit="per-day",
        baseline_effort=2,
        cost_usd=0.0,
        duration_minutes=3,
        needs_learning=False,
        description="Vampire power is easy quicksand to eliminate.",
    ),
    ActionTemplate(
        action_id="energy_laundry_cold",
        title="Wash one load on cold",
        category=ImpactCategory.ENERGY,
        impact=ImpactVector(kwh=0.6),
        execution_unit="per-week",
        baseline_effort=2,
        cost_usd=0.0,
        duration_minutes=5,
        needs_learning=False,
        description="Cold wash uses a fraction of the energy of hot.",
    ),
    ActionTemplate(
        action_id="energy_vent_smart_dry",
        title="Line-dry one load instead of the dryer",
        category=ImpactCategory.ENERGY,
        impact=ImpactVector(kwh=2.5),
        execution_unit="per-week",
        baseline_effort=3,
        cost_usd=0.0,
        duration_minutes=10,
        needs_learning=False,
        description="Dryers are among the hungriest appliances in the home.",
    ),
    ActionTemplate(
        action_id="water_tap_off",
        title="Turn the tap off while brushing / scrubbing",
        category=ImpactCategory.WATER,
        impact=ImpactVector(litres=12.0),
        execution_unit="per-day",
        baseline_effort=1,
        cost_usd=0.0,
        duration_minutes=0,
        needs_learning=False,
        description="A running tap wastes litres a minute.",
    ),
    ActionTemplate(
        action_id="water_full_loads",
        title="Only run the dishwasher/washer when full",
        category=ImpactCategory.WATER,
        impact=ImpactVector(litres=25.0, kwh=0.2),
        execution_unit="per-week",
        baseline_effort=2,
        cost_usd=0.0,
        duration_minutes=0,
        needs_learning=False,
        description="Half-empty cycles use the same water as full ones.",
    ),
    ActionTemplate(
        action_id="water_plant_dawn",
        title="Water plants at dawn/dusk (not midday)",
        category=ImpactCategory.WATER,
        impact=ImpactVector(litres=20.0),
        execution_unit="per-week",
        baseline_effort=2,
        cost_usd=0.0,
        duration_minutes=5,
        needs_learning=False,
        description="Less evaporation, plants still thrive.",
    ),
    ActionTemplate(
        action_id="water_leak_check",
        title="Check one tap/pipe for a leak",
        category=ImpactCategory.WATER,
        impact=ImpactVector(litres=60.0),
        execution_unit="one-time",
        baseline_effort=3,
        cost_usd=3.0,
        duration_minutes=15,
        needs_learning=False,
        description="A slow leak can waste hundreds of litres a day.",
    ),
    ActionTemplate(
        action_id="travel_plan_bike",
        title="Replace one short car trip with a bike/walk",
        category=ImpactCategory.TRANSPORT,
        impact=ImpactVector(co2e_kg=0.9),
        execution_unit="per-week",
        baseline_effort=4,
        cost_usd=0.0,
        duration_minutes=25,
        needs_learning=False,
        description="Short car trips are the easiest to shift.",
    ),
    ActionTemplate(
        action_id="travel_bundle_errands",
        title="Bundle errands into one trip",
        category=ImpactCategory.TRANSPORT,
        impact=ImpactVector(co2e_kg=0.5),
        execution_unit="per-week",
        baseline_effort=3,
        cost_usd=0.0,
        duration_minutes=5,
        needs_learning=False,
        description="One efficient route instead of several.",
    ),
    ActionTemplate(
        action_id="travel_bus_commute",
        title="Take public transit for one commute",
        category=ImpactCategory.TRANSPORT,
        impact=ImpactVector(co2e_kg=1.4),
        execution_unit="per-week",
        baseline_effort=5,
        cost_usd=2.0,
        duration_minutes=10,
        needs_learning=True,
        description="Transit per-km emissions are far below solo driving.",
    ),
    ActionTemplate(
        action_id="travel_carpool",
        title="Carpool or share one trip",
        category=ImpactCategory.TRANSPORT,
        impact=ImpactVector(co2e_kg=0.8),
        execution_unit="per-week",
        baseline_effort=4,
        cost_usd=0.0,
        duration_minutes=10,
        needs_learning=False,
        description="Sharing a ride halves per-person emissions.",
    ),
    ActionTemplate(
        action_id="food_freezer_surplus",
        title="Freeze leftovers/surplus food the same day",
        category=ImpactCategory.FOOD,
        impact=ImpactVector(kg_food=0.4),
        execution_unit="per-week",
        baseline_effort=3,
        cost_usd=0.0,
        duration_minutes=5,
        needs_learning=False,
        description="Freezing turns would-be waste into future meals.",
    ),
    ActionTemplate(
        action_id="food_plant_meal",
        title="Swap one meal to plant-based",
        category=ImpactCategory.FOOD,
        impact=ImpactVector(co2e_kg=0.5),
        execution_unit="per-week",
        baseline_effort=4,
        cost_usd=0.0,
        duration_minutes=10,
        needs_learning=True,
        description="Plant-based meals have a fraction of the footprint.",
    ),
    ActionTemplate(
        action_id="food_bulk_ugly",
        title="Buy one imperfect/ugly produce item",
        category=ImpactCategory.FOOD,
        impact=ImpactVector(kg_food=0.25, kg=0.25),
        execution_unit="per-week",
        baseline_effort=2,
        cost_usd=1.0,
        duration_minutes=2,
        needs_learning=False,
        description="Visually imperfect produce is often wasted at farm level.",
    ),
    ActionTemplate(
        action_id="food_buy_local",
        title="Buy one local seasonal item",
        category=ImpactCategory.FOOD,
        impact=ImpactVector(co2e_kg=0.3),
        execution_unit="per-week",
        baseline_effort=3,
        cost_usd=2.0,
        duration_minutes=5,
        needs_learning=False,
        description="Less transport and cold chain per meal.",
    ),
    ActionTemplate(
        action_id="buy_wait_48h",
        title="Apply a 48-hour wait before one non-essential purchase",
        category=ImpactCategory.CONSUMPTION,
        impact=ImpactVector(items=1.0, kg=0.3),
        execution_unit="per-week",
        baseline_effort=4,
        cost_usd=0.0,
        duration_minutes=5,
        needs_learning=False,
        description="Turns impulse into intention; many purchases fade away.",
    ),
    ActionTemplate(
        action_id="buy_secondhand",
        title="Buy one item second-hand",
        category=ImpactCategory.CONSUMPTION,
        impact=ImpactVector(items=1.0, kg=0.8),
        execution_unit="per-month",
        baseline_effort=5,
        cost_usd=5.0,
        duration_minutes=30,
        needs_learning=False,
        description="New production avoided; a used item is almost 'free' impact.",
    ),
    ActionTemplate(
        action_id="buy_repair_tool",
        title="Repair the 'almost broken' item",
        category=ImpactCategory.CONSUMPTION,
        impact=ImpactVector(kg=0.5, items=1.0),
        execution_unit="per-month",
        baseline_effort=5,
        cost_usd=8.0,
        duration_minutes=45,
        needs_learning=True,
        description="Repair beats replace for both wallet and planet.",
    ),
    ActionTemplate(
        action_id="buy_capsule_check",
        title="Do a 10-minute 'do I need this?' capsule check",
        category=ImpactCategory.CONSUMPTION,
        impact=ImpactVector(items=1.0),
        execution_unit="per-month",
        baseline_effort=2,
        cost_usd=0.0,
        duration_minutes=10,
        needs_learning=False,
        description="A tiny audit of one purchase avoids landfill later.",
    ),
]


def get_template(action_id: str) -> ActionTemplate | None:
    return next((t for t in LIBRARY if t.action_id == action_id), None)


def templates_for_category(category: ImpactCategory) -> list[ActionTemplate]:
    return [t for t in LIBRARY if t.category == category]


def all_templates() -> list[ActionTemplate]:
    return list(LIBRARY)
